### ISSUE TITLE
Issue Generating Readme based on repository

### ISSUE THREAD

**Issue by AstraVision-Labs** [mazshakibaii/reppy#1]
![2024_11_16_07_05_53_New_Issue_mazshakibaii_reppy](https://github.com/user-attachments/assets/6de75e93-db26-4ec3-8b7d-f325bf3ed082)

I am getting following error, after scanning thru the codebase, it is excellent, but unable to finish documenting, Can you suggest how to overcome the challenge.

Regards,
PA

**Comment by mazshakibaii** [comment]
> ![2024_11_16_07_05_53_New_Issue_mazshakibaii_reppy](https://github.com/user-attachments/assets/6de75e93-db26-4ec3-8b7d-f325bf3ed082)
> 
> 
> 
> I am getting following error, after scanning thru the codebase, it is excellent, but unable to finish documenting, Can you suggest how to overcome the challenge.
> 
> 
> 
> Regards,
> 
> PA
> 
> 
> 
> 

Thanks for the kind words! It looks like this is a big codebase so it's exceeding the input token limit for the LLM you're using.

Which LLM is this? If you're using an OpenAI model, try using the Anthropic Claude 3.5 Sonnet model instead as it has a larger context window.
